feat: DSW-1463: Add component to pie aperture (NextJS & Vanilla)
justeattakeaway/pie-aperture pull request #104
Opened 2024-04-06 00:30 UTC by thejfreitas

In this PR I am adding pie-notification into NextJS and Vanilla Apps.

### Screenshots

![Screenshot 2024-04-05 at 6 26 27 PM](https://github.com/justeattakeaway/pie-aperture/assets/7768202/56b84501-46d0-4976-9a7a-bcceb8cb5850)
![Screenshot 2024-04-05 at 6 25 54 PM](https://github.com/justeattakeaway/pie-aperture/assets/7768202/1ba62b14-1d12-4ac2-806b-f1d5519c228f)

2024-04-08 14:44 UTC, raoufswe approved these changes

2024-04-08 14:45 UTC, raoufswe commented on vanilla-app/js/notification.js
> +var $notification = document.querySelector('#notification');
let's use a const or let here

2024-04-15 10:15 UTC, raoufswe submitted a review, later dismissed

2024-04-22 15:20 UTC, siggerzz requested changes
Minor comment regarding fixed dependency versions.

Also it doesn't have to be in this PR, but if you wouldn't mind doing a follow-up PR to add a visual test (click the 'Open notification' button and take a screenshot), that would be much appreciated!

It would be great if we had some system tests too, to check that when the close / confirm are clicked, the notification is dismissed.

The DS team will be happy to assist you with these if needed!

2024-04-22 15:37 UTC, raoufswe submitted a review, later dismissed

2024-04-24 13:53 UTC, raoufswe approved these changes

2024-04-24 14:08 UTC, siggerzz approved these changes

2024-04-24 14:10 UTC, merged